[issue]
user = "Kicksecure"
repo = "security-misc"
rev = "de6f3ea74a5a1408e4351c955ecb7010825364c5"
file = "usr/lib/issue.d/20_security-misc.issue"
sha256 = "00ilswn1661h8rwfrq4w3j945nr7dqd1g519d3ckfkm0dr49f26b"
modified = "2024/08/02"

[gitconfig]
user = "Kicksecure"
repo = "security-misc"
rev = "de6f3ea74a5a1408e4351c955ecb7010825364c5"
file = "etc/gitconfig"
sha256 = "1p3adrbmv7fvy84v3i3m3xrzbc2zdrxzn6prac8f6418vwrdmyp7"
modified = "2024/08/02"

[bluetooth]
user = "Kicksecure"
repo = "security-misc"
rev = "de6f3ea74a5a1408e4351c955ecb7010825364c5"
file = "etc/bluetooth/30_security-misc.conf"
sha256 = "0xyvvgmm0dhf0dfhfj4hdbyf2ma30bpd1m5zx6xnjdfvy2fr44na"
modified = "2024/08/02"

[module-blacklist]
user = "Kicksecure"
repo = "security-misc"
rev = "de6f3ea74a5a1408e4351c955ecb7010825364c5"
file = "etc/modprobe.d/30_security-misc_disable.conf"
sha256 = "1mab9cnnwpc4a0x1f5n45yn4yhhdy1affdmmimmslg8rcw65ajh2"
modified = "2024/08/02"

[chrony]
user = "GrapheneOS"
repo = "infrastructure"
rev = "1f4d7316b8bd42476fc8e98224f67ce8d150527d"
file = "etc/chrony.conf"
sha256 = "sha256:0cfd5dwimiv4sadmknnc4l4zm7y49bmdnjdk7wc8wvnhfri3mick"
modified = "2025/04/16"